[build]
  command = "npm run build:netlify"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  # Copy database file to functions directory
  included_files = [
    "dev.db",
    "prisma/**",
    "node_modules/.prisma/client/**"
  ]

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  DATABASE_URL = "file:./dev.db"
