[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
# Skip devDependencies during Netlify install to avoid vite/vitest peer conflicts
  NPM_FLAGS = "--omit=dev"
