[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
# Install devDependencies during build so Prisma can generate the client.
# Using legacy peer deps to avoid transient peer conflicts from test tooling.
  NPM_FLAGS = "--legacy-peer-deps"
