[build]
  command = "npm run build:netlify"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Scheduled functions configuration
[functions]
  directory = "netlify/functions"
  included_files = ["dev.db", "netlify/functions/dev.db"]

[build.environment]
# Install devDependencies during build so Prisma can generate the client.
# Using legacy peer deps to avoid transient peer conflicts from test tooling.
  NPM_FLAGS = "--legacy-peer-deps"
  DATABASE_URL = "file:${PWD}/dev.db"
